### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by 123789456ye** [fsy2001/fudan-sport-automator#11]
本学期开始用才发现加了个异步
设置定时之后回来检查发现没跑上，在检查日志之后又去检查参数才发现必须在main.py所在位置运行才不会报错
系统是ubuntu22.04 on wsl2
![image](https://github.com/fsy2001/fudan-sport-automator/assets/51439899/cc7d4d1e-f623-4ece-aa13-1d407bc3a661)
![image](https://github.com/fsy2001/fudan-sport-automator/assets/51439899/32b115c8-04c2-496d-8725-b7fed30d5b67)

**Comment by fsy2001** [comment]
@BiologyHazard

**Comment by BiologyHazard** [comment]
一般不都默认在工作区根目录（.gitignore所在目录）运行吗（
因为settings.json写的是相对目录，所以工作目录在其他目录就读不了这个文件了

**Comment by 123789456ye** [comment]
> 一般工作路径不都默认是工作区根目录（`.gitignore`所在目录）吗（ 因为在`_get_arg_from_env_or_json`函数中，从`settings.json`写的是相对目录，所以工作目录在其他目录就读不了这个文件了

原来是这里啊（
写脚本的时候直接摆个绝对路径导致的

**Comment by BiologyHazard** [comment]
解决方案
1. 把`sports_api.py, line 13`中`'settings.json'`替换成`Path(__file__).parent / 'settings.json'`
2. 运行之前先`cd`到`.gitignore`所在目录
