### ISSUE TITLE
被制裁力

### ISSUE THREAD

**Issue by BiologyHazard** [fsy2001/fudan-sport-automator#15]
上线一看发现会返回“签名失败”
```json
{
    "name": "Precondition Failed",
    "message": "签名失败",
    "code": 412,
    "status": 412
}
```

然后小程序发`GET`请求的url大概变成了
`https://sport.fudan.edu.cn/sapi/run/start?userid=****&token=****&route_id=43&route_type=4&system=Windows%2011%20x64&device=microsoft%7Cmicrosoft&lng=121.52609252929688&lat=31.259559631347656&sign=43e856e6c**********75e41922d92a3`

有办法获取sign吗

被制裁力（悲）

**Comment by fsy2001** [comment]
哈哈 我体育课都上完啦🤣

**Comment by fsy2001** [comment]
私钥应该在本地，有空逆向一下试试

**Comment by BiologyHazard** [comment]
确实，sign和时间没关系，盐应该只可能在程序里

**Comment by mushichou** [comment]
sign应该是根据字典加密的，所以三天sign应该才会变一次吧

**Comment by BiologyHazard** [comment]
> sign应该是根据字典加密的，所以三天sign应该才会变一次吧

不是啊，sign是对数据包和密钥哈希得到的

**Comment by BiologyHazard** [comment]
> 私钥应该在本地，有空逆向一下试试

大佬加油

**Comment by fsy2001** [comment]
done
