### ISSUE TITLE
不懂就问

### ISSUE THREAD

**Issue by 123789456ye** [fsy2001/fudan-sport-automator#17]
怎么破解出'moveclub123123123'的啊？自己试了下也能确定有这些参数，但是还加的盐只知道应该是固定的，感觉试不出来就弃了
以及如果加时间/随机盐有办法处理吗？

**Comment by fsy2001** [comment]
#16 里 @habacat 提供了小程序的源码，`api/request.js:20` 是计算 sign 的函数

**Comment by 123789456ye** [comment]
这也能？
感恩

**Comment by BiologyHazard** [comment]
这怎么逆出来的，孩子想学qwq

**Comment by fsy2001** [comment]
其实网上搜搜微信小程序逆向会有很多教程的，而且有现成的工具，只不过都是基于安卓和windows的，我一样都没有😇
