### ISSUE TITLE
用cmd运行反复报错无geopy文件

### ISSUE THREAD

**Issue by Tenarial** [fsy2001/fudan-sport-automator#2]
![屏幕截图 2023-05-19 115526](https://github.com/fsy2001/fudan-sport-automator/assets/133988339/8e390a75-f7c6-44e9-92ff-f1a4dbb41019)

**Comment by fsy2001** [comment]
你需要 `pip install -r requirements.txt`

**Comment by fsy2001** [comment]
在 README 中新增了本地运行的教程，无需配置依赖，请参考。
