### ISSUE TITLE
探索更舒适的使用方式

### ISSUE THREAD

**Issue by habacat** [fsy2001/fudan-sport-automator#20]
想个办法看看能不能不通过抓包获取id和token？抓包对于大部分友友的难度还是比较大的。

**Comment by habacat** [comment]
一开始想得太简单了，wxcode()不知道怎么生成的，是微信内部的函数。有效期5分钟，用完即废╮(╯▽╰)╭
通过wxcode获取unionid和session_key，然后才能进行处理。
wxcode本身依赖微信特殊协议，同时还需要appid和appsecret，解包发现"appid": "wxba754687f9ae3c33"，但是secret找不到，这又是一个麻烦。

综上，先把这个issue给关了吧~麻烦楼主

**Comment by fsy2001** [comment]
微信小程序登录流程可以参看 [这个页面](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/login.html)，要获取到登录所须信息，必须逆向微信客户端与腾讯服务器之间通信的私有协议，难度比较大。

**Comment by fsy2001** [comment]
复旦服务器在收到登录信息之后，会和微信服务器校验，因此传送伪造的登录信息是无法获取到token的。
