### ISSUE TITLE
本地运行报错：远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by cesoiroujemais** [fsy2001/fudan-sport-automator#28]
求助：大部分时间程序可以正常运行，偶尔会在运行一段时间后报错“远程主机强迫关闭了一个现有的连接”，然后中止运行。目前没观察到这个报错的出现有什么规律，猜测可能是随机的。
请问这种情况是为什么呢？应该怎样解决呀？非常感谢！！
下面是运行到一半报错的程序截图：
![06d1b00e1c3ba216cfcd0c996e8a127](https://github.com/fsy2001/fudan-sport-automator/assets/132743489/75afdc19-eed5-40f7-a270-13130b971c82)
![d11d6881de1cd9036ca9ae62398cd41](https://github.com/fsy2001/fudan-sport-automator/assets/132743489/58ac38b9-49dd-4f17-b30d-5955336f0c59)

**Comment by BiologyHazard** [comment]
因为`response = requests.get(update_url, params=params, verify=False)`
https://github.com/fsy2001/fudan-sport-automator/blob/d6995837c0f846bcdeea8dc651e729a8f29281db/sport_api.py#L79
这句话没写在try语句里面，如果get请求发生错误，程序直接崩溃了。
可能的解决方案是`try: ... except Exception: pass`
@fsy2001

**Comment by BiologyHazard** [comment]
如果要直接修复这个问题，不要直接把这句话移到下面那行的`try`语句块中，否则跳转到`except`字句的时候`response`未被赋值，而无法返回`response.text`
~~要不然，直接`print(exception)`得了~~

**Comment by fsy2001** [comment]
done

**Comment by fsy2001** [comment]
下载最新的release即可。目前最新的应该是v2.1.2

**Comment by cesoiroujemais** [comment]
> 下载最新的release即可。目前最新的应该是v2.1.2

感谢！！
