### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by liquorxty** [fsy2001/fudan-sport-automator#5]
<img width="496" alt="b6621754f89c3a2f76457d081e0722b" src="https://github.com/fsy2001/fudan-sport-automator/assets/133321947/59bc9dd6-091c-474d-afd4-e1cbf65880b6">
为什么会这样

**Comment by fsy2001** [comment]
报错信息里写了是你的 Token 错误，你的 Token 可能过期了（有效期 3 天），或者复制的时候出错了。Token 的格式是数字和字母组成的，开头和结尾都没有空格。你可以再检查一遍。以及 User ID 是一个纯数字，也可以一并检查。

**Comment by liquorxty** [comment]
下午看的时候token是另一个但不行，现在token变了我也改了，然后可以。再问一下早操的话必须按时爬起来输一下是吗。

**Comment by liquorxty** [comment]
> 报错信息里写了是你的 Token 错误，你的 Token 可能过期了（有效期 3 天），或者复制的时候出错了。Token 的格式是数字和字母组成的，开头和结尾都没有空格。你可以再检查一遍。以及 User ID 是一个纯数字，也可以一并检查。

下午看的时候token是另一个但不行，现在token变了我也改了，然后可以。再问一下早操的话必须按时爬起来输一下是吗。

**Comment by fsy2001** [comment]
目前是的，之后可能会增加定时任务功能。目前你也可以在网上自行搜索 Windows 如何添加定时任务。
